### ISSUE TITLE
开卡脚本一直报错~

### ISSUE THREAD

**Issue by boopzk22** [Tsukasa007/my_script#5]
跑一半或者刚跑就
"Response code 493 (undefined)"
7.28-7.31 特物-拉满BUFF 漂亮上场 API请求失败，请检查网路重试

❗️7.28-7.31 特物-拉满BUFF 漂亮上场, 错误!
TypeError: Cannot read property 'secretPin' of undefined
    at /ql/scripts/jd_TW_buff.js:79:76
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by Tsukasa007** [comment]
更新一下代码再试试

**Comment by boopzk22** [comment]
"read ECONNRESET"
7.26-8.8 全民奔跑 激扬奥运 API请求失败，请检查网路重试
(node:707) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'token' of undefined
    at /ql/scripts/raw_jd_olympic_opencard.js:333:22
    at /ql/scripts/raw_jd_olympic_opencard.js:500:5858
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> 更新一下代码再试试

jd_olympic_opencard.js 这个脚本也会遇到报错~
7.26-8.8 全民奔跑 激扬奥运 API请求失败，请检查网路重试
"Response code 493 (undefined)"
7.26-8.8 全民奔跑 激扬奥运 API请求失败，请检查网路重试
(node:5143) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'actorUuid' of undefined
    at /ql/scripts/jd_olympic_opencard.js:458:27
    at /ql/scripts/jd_olympic_opencard.js:499:5858
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Tsukasa007** [comment]
好像是因为是黑号

**Comment by Tsukasa007** [comment]
我家了判断再试试吧

**Comment by boopzk22** [comment]
> 我加了判断再试试吧

好像可以了，大佬辛苦！有tg群嘛~

**Comment by Tsukasa007** [comment]
github就是我的家
