### ISSUE TITLE
❗️7.26-8.8 全民奔跑 激扬奥运, 错误! 抽奖报错

### ISSUE THREAD

**Issue by piaoyun** [Tsukasa007/my_script#6]
❗️7.26-8.8 全民奔跑 激扬奥运, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /jd/scripts/jd_olympic_opencard.js:176:32
    at got.post.then.message (/jd/scripts/jd_olympic_opencard.js:503:5772)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️7.26-8.8 全民奔跑 激扬奥运, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /jd/scripts/jd_olympic_opencard.js:234:23
    at got.post.then.message (/jd/scripts/jd_olympic_opencard.js:503:5772)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
nowScore: 50

**Comment by Tsukasa007** [comment]
这是哪跑的
